name: crochet_mate
description: A crochet project management app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  sqflite: ^2.3.0
  image_picker: ^1.0.2
  path: ^1.8.3
  intl: ^0.19.0
  uuid: ^4.0.0
  confetti: ^0.8.0
  flutter_markdown: ^0.7.6
  url_launcher: ^6.1.14
  share_plus: ^10.1.4
  pdf: ^3.10.4
  open_file: ^3.3.2
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  build_runner: ^2.4.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/splash/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  adaptive_icon_round: true
  remove_alpha_ios: true
  min_sdk_android: 21
 
