import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static const String _languageKey = 'selected_language';
  final SharedPreferences _prefs;
  String _currentLanguage = 'es';

  LocalizationService(this._prefs) {
    _currentLanguage = _prefs.getString(_languageKey) ?? 'es';
  }

  String get currentLanguage => _currentLanguage;

  static final Map<String, Map<String, String>> _localizedStrings = {
    'es': {
      'app_title': 'CrochetMate',
      'projects': 'Mis Proyectos',
      'patterns': 'Patrones',
      'counters': 'Contadores',
      'settings': 'Ajustes',
      'search_patterns': 'Buscar patrones...',
      'new_pattern': 'Nuevo Patrón',
      'edit_pattern': 'Editar Patrón',
      'pattern_name': 'Nombre del patrón',
      'description': 'Descripción',
      'difficulty': 'Dificultad',
      'instructions': 'Instrucciones',
      'beginner': 'Principiante',
      'intermediate': 'Intermedio',
      'advanced': 'Avanzado',
      'expert': 'Experto',
      'no_patterns': 'No hay patrones guardados',
      'create_pattern': 'Crea o importa un patrón nuevo',
      'language_changed_es': 'Idioma cambiado a Español',
      'filter_by_difficulty': 'Filtrar por dificultad',
      'all': 'Todos',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',
      'theme': 'Tema',
      'select_theme': 'Seleccionar tema',
      'system': 'Sistema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'error_loading_patterns': 'Error al cargar los patrones',
      'error_exporting_pdf': 'Error al exportar el PDF',
      'search_projects': 'Buscar proyectos...',
      'new_project': 'Nuevo Proyecto',
      'edit_project': 'Editar Proyecto',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'export': 'Exportar',
      'import': 'Importar',
      'confirm': 'Confirmar',
      'yes': 'Sí',
      'no': 'No',
      'enter_pattern_name': 'Por favor ingresa un nombre',
      'pattern_name_label': 'Nombre del patrón',
      'description_label': 'Descripción',
      'instructions_label': 'Instrucciones',
      'difficulty_label': 'Dificultad',
      'save_pattern': 'Guardar patrón',
      'delete_pattern': 'Eliminar patrón',
      'confirm_delete': '¿Estás seguro de que deseas eliminar este patrón?',
      'pattern_saved': 'Patrón guardado exitosamente',
      'pattern_deleted': 'Patrón eliminado exitosamente',
      'error_saving': 'Error al guardar el patrón',
      'error_deleting': 'Error al eliminar el patrón',
      'spanish': 'Español',
      'english': 'English',
      'no_projects': 'No hay proyectos guardados',
      'no_counters': 'No hay contadores guardados',
      'create_counter': 'Crear contador',
      'edit_counter': 'Editar contador',
      'counter_name': 'Nombre del contador',
      'current_count': 'Conteo actual',
      'app_subtitle': 'Tu compañero de crochet',
      'manage_projects': 'Gestiona tus proyectos',
      'explore_patterns': 'Explora patrones',
      'count_rounds': 'Cuenta tus vueltas',
      'customize_app': 'Personaliza la app',
      'language_es': 'Español',
      'language_en': 'English',
      'project_name': 'Nombre del proyecto',
      'enter_project_name': 'Por favor ingresa un nombre',
      'add_round': 'Añadir ronda',
      'hook_size': 'Tamaño del gancho',
      'yarn_type': 'Tipo de hilo',
      'status': 'Estado',
      'deadline': 'Fecha límite',
      'rounds': 'Rondas',
      'add_image': 'Añadir imagen',
      'in_progress': 'En progreso',
      'completed': 'Completado',
      'abandoned': 'Abandonado',
      'new_counter': 'Nuevo Contador',
      'enter_counter_name': 'Por favor ingresa un nombre para el contador',
      'reset': 'Reiniciar',
      'increment': 'Incrementar',
      'decrement': 'Decrementar',
      'delete_counter': 'Eliminar contador',
      'confirm_delete_counter':
          '¿Estás seguro de que deseas eliminar este contador?',
      'counter_saved': 'Contador guardado exitosamente',
      'counter_deleted': 'Contador eliminado exitosamente',
      'error_saving_counter': 'Error al guardar el contador',
      'error_deleting_counter': 'Error al eliminar el contador',
      'tutorial_welcome_title': '¡Bienvenido a CrochetMate!',
      'tutorial_welcome_desc':
          'Tu compañero perfecto para tus proyectos de crochet. Vamos a explorar las principales funciones.',
      'tutorial_projects_title': 'Proyectos',
      'tutorial_projects_desc':
          'Aquí podrás gestionar todos tus proyectos de crochet, con fotos, notas y seguimiento de progreso.',
      'tutorial_patterns_title': 'Patrones',
      'tutorial_patterns_desc':
          'Explora y guarda tus patrones favoritos. Puedes crear los tuyos propios o importar otros.',
      'tutorial_counters_title': 'Contadores',
      'tutorial_counters_desc':
          'Lleva el control de tus vueltas con contadores personalizables para cada proyecto.',
      'show_tutorial': 'Ver tutorial',
      'show_tutorial_desc': 'Vuelve a ver el tutorial de introducción',
      'previous': 'Anterior',
      'next': 'Siguiente',
      'finish': 'Finalizar',
      'preview': 'Vista Previa',
      'round': 'Ronda',
      'no_instructions': 'Sin instrucciones',
      'new_counter_dialog_title': 'Nuevo Contador',
      'counter_name_hint': 'Ej: Proyecto Amigurumi',
      'create': 'Crear',
      'deadline_title': 'Fecha límite',
      'no_deadline': 'Sin fecha límite',
      'round_undone': 'Vuelta deshecha',
      'undo': 'Deshacer',
      'project_details': 'Detalles del Proyecto',
    },
    'en': {
      'app_title': 'CrochetMate',
      'projects': 'My Projects',
      'patterns': 'Patterns',
      'counters': 'Counters',
      'settings': 'Settings',
      'search_patterns': 'Search patterns...',
      'new_pattern': 'New Pattern',
      'edit_pattern': 'Edit Pattern',
      'pattern_name': 'Pattern name',
      'description': 'Description',
      'difficulty': 'Difficulty',
      'instructions': 'Instructions',
      'beginner': 'Beginner',
      'intermediate': 'Intermediate',
      'advanced': 'Advanced',
      'expert': 'Expert',
      'no_patterns': 'No patterns saved',
      'create_pattern': 'Create or import a new pattern',
      'language_changed_en': 'Language changed to English',
      'filter_by_difficulty': 'Filter by difficulty',
      'all': 'All',
      'language': 'Language',
      'select_language': 'Select language',
      'theme': 'Theme',
      'select_theme': 'Select theme',
      'system': 'System',
      'light': 'Light',
      'dark': 'Dark',
      'error_loading_patterns': 'Error loading patterns',
      'error_exporting_pdf': 'Error exporting PDF',
      'search_projects': 'Search projects...',
      'new_project': 'New Project',
      'edit_project': 'Edit Project',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'export': 'Export',
      'import': 'Import',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'enter_pattern_name': 'Please enter a name',
      'pattern_name_label': 'Pattern name',
      'description_label': 'Description',
      'instructions_label': 'Instructions',
      'difficulty_label': 'Difficulty',
      'save_pattern': 'Save pattern',
      'delete_pattern': 'Delete pattern',
      'confirm_delete': 'Are you sure you want to delete this pattern?',
      'pattern_saved': 'Pattern saved successfully',
      'pattern_deleted': 'Pattern deleted successfully',
      'error_saving': 'Error saving pattern',
      'error_deleting': 'Error deleting pattern',
      'spanish': 'Spanish',
      'english': 'English',
      'no_projects': 'No projects saved',
      'no_counters': 'No counters saved',
      'create_counter': 'Create counter',
      'edit_counter': 'Edit counter',
      'counter_name': 'Counter name',
      'current_count': 'Current count',
      'app_subtitle': 'Your crochet companion',
      'manage_projects': 'Manage your projects',
      'explore_patterns': 'Explore patterns',
      'count_rounds': 'Count your rounds',
      'customize_app': 'Customize the app',
      'language_es': 'Spanish',
      'language_en': 'English',
      'project_name': 'Project name',
      'enter_project_name': 'Please enter a name',
      'add_round': 'Add round',
      'hook_size': 'Hook Size',
      'yarn_type': 'Yarn Type',
      'status': 'Status',
      'deadline': 'Deadline',
      'rounds': 'Rounds',
      'add_image': 'Add image',
      'in_progress': 'In progress',
      'completed': 'Completed',
      'abandoned': 'Abandoned',
      'new_counter': 'New Counter',
      'enter_counter_name': 'Please enter a counter name',
      'reset': 'Reset',
      'increment': 'Increment',
      'decrement': 'Decrement',
      'delete_counter': 'Delete counter',
      'confirm_delete_counter': 'Are you sure you want to delete this counter?',
      'counter_saved': 'Counter saved successfully',
      'counter_deleted': 'Counter deleted successfully',
      'error_saving_counter': 'Error saving counter',
      'error_deleting_counter': 'Error deleting counter',
      'tutorial_welcome_title': 'Welcome to CrochetMate!',
      'tutorial_welcome_desc':
          'Your perfect companion for your crochet projects. Let\'s explore the main features.',
      'tutorial_projects_title': 'Projects',
      'tutorial_projects_desc':
          'Here you can manage all your crochet projects, with photos, notes and progress tracking.',
      'tutorial_patterns_title': 'Patterns',
      'tutorial_patterns_desc':
          'Explore and save your favorite patterns. You can create your own or import others.',
      'tutorial_counters_title': 'Counters',
      'tutorial_counters_desc':
          'Keep track of your rounds with customizable counters for each project.',
      'show_tutorial': 'Show tutorial',
      'show_tutorial_desc': 'See the introduction tutorial again',
      'previous': 'Previous',
      'next': 'Next',
      'finish': 'Finish',
      'preview': 'Preview',
      'round': 'Round',
      'no_instructions': 'No instructions',
      'new_counter_dialog_title': 'New Counter',
      'counter_name_hint': 'Ex: Amigurumi Project',
      'create': 'Create',
      'deadline_title': 'Deadline',
      'no_deadline': 'No deadline',
      'round_undone': 'Round undone',
      'undo': 'Undo',
      'project_details': 'Project Details',
    },
  };

  Future<void> setLanguage(String languageCode) async {
    if (_currentLanguage != languageCode) {
      await _prefs.setString(_languageKey, languageCode);
      _currentLanguage = languageCode;
      notifyListeners();
    }
  }

  String translate(String key) {
    return _localizedStrings[_currentLanguage]?[key] ?? key;
  }

  Map<String, String> getAllTranslationsForLanguage(String languageCode) {
    return _localizedStrings[languageCode] ?? {};
  }

  Future<String> getLanguage() async {
    return _prefs.getString(_languageKey) ?? 'es';
  }
}
